# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: replication.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'replication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11replication.proto\x12\x0breplication\"P\n\x18ReplicationUpdateRequest\x12\x11\n\tupdate_id\x18\x01 \x01(\t\x12\x13\n\x0bupdate_type\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"=\n\x19ReplicationUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2v\n\x12ReplicationService\x12`\n\x0fReplicateUpdate\x12%.replication.ReplicationUpdateRequest\x1a&.replication.ReplicationUpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'replication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REPLICATIONUPDATEREQUEST']._serialized_start=34
  _globals['_REPLICATIONUPDATEREQUEST']._serialized_end=114
  _globals['_REPLICATIONUPDATERESPONSE']._serialized_start=116
  _globals['_REPLICATIONUPDATERESPONSE']._serialized_end=177
  _globals['_REPLICATIONSERVICE']._serialized_start=179
  _globals['_REPLICATIONSERVICE']._serialized_end=297
# @@protoc_insertion_point(module_scope)
